eureka:
  client:
    service-url:
      default zone: http://localhost:8761/eureka
    fetch-registry: true

server:
  port: 8080

spring:
  application:
    name: zuul

management:
  endpoints:
    web:
      exposure:
        include: "*"
