server:
  port: 9001

#??????????name,?name??????????????(??id)
spring:
  application:
    name: user-provider
  datasource:
    druid:
      #???8.X???????????:com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      #???8.X??????url???????(  serverTimezone=UTC )
      url: jdbc:mysql://localhost:3306/pratice?userSSL=false&serverTimezone=UTC
      username: root
      #?????
      password: root
mybatis:
  #mapper???????
  mapper-locations: classpath:mappers/*Mapper.xml
  #???????????(?Mapper?????????????????????????)
  type-aliases-package: com.example.goodscommon.pojo

#????????? '?????????'???
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka
    fetch-registry: true


